### ISSUE TITLE
Any chance of getting this to work with Nancy Razor?

### ISSUE THREAD

**Issue by tofutim** [jkommer/GravatarHelper#2]
i think with ASPNETCore support it is close.

**Comment by jkommer** [comment]
I've never used Nancy before - but I'll have a look into it over the weekend.

**Comment by tofutim** [comment]
In the interim, I stuck Gravatar into my ViewModel

`		public UserViewModel(ClaimsPrincipal principal)
		{
			_principal = principal;
			_userId = principal.GetUserId();

			if (IsAuthenticated)
			{
				_provider = principal.GetIdentityProvider();
				_name = principal.GetName();
				_email = principal.GetEmail();
				_gravatarUrl = GravatarHelper.Common.GravatarHelper.CreateGravatarUrl(
					_email, 80, GravatarHelper.Common.GravatarHelper.DefaultImageIdenticon,
					GravatarHelper.Common.GravatarRating.X, false, false, true);
			}
		}`

**Comment by jkommer** [comment]
Ok, I've had a quick look into it and it seemed easy enough - could you try the  [GravatarHelper.Nancy.Razor](https://ci.appveyor.com/project/jkommer/gravatarhelper/build/1.0.70/artifacts)  package and see if this works for you? 

It worked for me in the Nancy Sample application for both `@Url` and `@Html`. Please note that you'll need to add `@using GravatarHelper.Nancy.Razor.Extensions' to your view currently, as I've not been able to get things to work through a namespace import in the Web.config just yet.

**Comment by jkommer** [comment]
@tofutim - Have you had a chance to look at this? If it's all working I'll publish it to the NuGet Gallery later today.

**Comment by jkommer** [comment]
Closing this issue as the request seems abandoned.
