### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by JohnNickerson** [jkommer/GravatarHelper#3]
I had to add "@using GravatarHelper.Extensions" to my Razor view for MVC 5.2.4 before I could use the "@Html.Gravatar" method. I didn't find that step documented here. It's a small step, and it may seem obvious, but I had to discover it by myself.

**Comment by jkommer** [comment]
Would you be able to confirm whether you installed the library through NuGet or through other means (e.g. manual)? The using statements should have been added to the Views/web.config file automatically by NuGet but I've not tested this in any non-visual studio environment. 

The docs should hopefully be updated tomorrow with the two expected using statements for manual installations / problem shooting.

**Comment by JohnNickerson** [comment]
I installed via the NuGet visual package manager in Visual Studio 2017. I can see that the Views/web.config file was also updated, but I still need the explicit "@using" statement in the view to use the extension method.

**Comment by jkommer** [comment]
Hi John,

I've updated the documentation with a troubleshooting section regarding the namespaces. I've tried replicating the issue in my own installation of Visual Studio 2017 but have unfortunately not run into any trouble myself with the namespaces in the web.config not working. But hopefully the documentation update should cover this case for now
