### ISSUE TITLE
The secure.gravatar.com URI no longer works

### ISSUE THREAD

**Issue by cskardon** [jkommer/GravatarHelper#4]
The documentation on Gravatar says the `https` endpoint is now: `https://www.gravatar.com` - and on my site - I've noticed that the `https://secure.gravatar.com` connection is now telling me it's refused.

**Comment by jkommer** [comment]
Thanks for the pull-request!

The updated NuGet packages should appear within the next hour or so while they are being indexed and validated by the gallery.
