### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by imclint21** [jkommer/GravatarHelper#6]
Hi,

Please add the https support, the link generated does not seem to be https.

Thank you

**Comment by jkommer** [comment]
Hi @clintnetwork ,

It should automatically switch to HTTPS if the current page is accessed over HTTPS - alternatively depending on which way you're using this library there are ways to force HTTPS everywhere e.g. through [gravatar-force-https](https://github.com/jkommer/GravatarHelper/blob/master/src/GravatarHelper.AspNetCore/TagHelpers/GravatarTagHelper.cs#L15) or through one of the `@Html` / `@Url` overloads in non-core MVC.

**Comment by imclint21** [comment]
Va very nice, I will try, it's crazy because I'm in https, you can see : https://clint.network

**Comment by jkommer** [comment]
Are you using an SSL terminating proxy / load balancer by any chance? As that would explain why it wouldn't automatically switch to HTTPS by default (as the requests from the proxy / load balancer would come in as http - rather than https).

**Comment by imclint21** [comment]
Yes now it's fixed nginx redirect to https now with hsts and I use force ssl gravatar configuration

**Comment by jkommer** [comment]
Thanks for confirming - I'll close the issue for now. 

I'll consider switching the default to always use HTTPS on the next release.

**Comment by imclint21** [comment]
Yes good idea
